name: Split and Upload Large File

on:
  workflow_dispatch:

jobs:
  split-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download large file with token
        run: |
          curl -L -o original.zip \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/octet-stream" \
          "https://api.github.com/repos/mamadmamadu11-dotcom/my-translation-model-entofa/actions/artifacts/6994355319/zip"
          
          echo "File downloaded. Size:"
          ls -lh original.zip

      - name: Split into 10MB chunks
        run: |
          mkdir chunks
          split -b 10m original.zip chunks/part_
          echo "Chunks created:"
          ls -lh chunks/

      - name: Upload chunks
        uses: actions/upload-artifact@v4
        with:
          name: whisper-chunks
          path: chunks/
          retention-days: 7
